#!/usr/bin/env python3
"""Generate OpenSCAD constants from the canonical SO-101/LeKiwi Xacro."""

from __future__ import annotations

import argparse
import math
import xml.etree.ElementTree as ET
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SO101 = ROOT / "cad/upstream/SO-ARM100/Simulation/SO101/so101_new_calib.urdf"
LEKIWI = ROOT / "URDF/LeKiwi.urdf.xacro"
OUTPUT = HERE / "generated/kinematics.scad"
JOINTS = (
    "shoulder_pan",
    "shoulder_lift",
    "elbow_flex",
    "wrist_flex",
    "wrist_roll",
    "gripper",
)


def vector(element: ET.Element, attribute: str, scale: float = 1.0) -> list[float]:
    values = [float(value) * scale for value in element.get(attribute).split()]
    if len(values) != 3 or not all(math.isfinite(value) for value in values):
        raise ValueError(f"invalid {attribute}: {element.get(attribute)!r}")
    return values


def number(value: float) -> str:
    value = 0.0 if abs(value) < 1e-9 else value
    return f"{value:.8g}"


def scad_vector(values: list[float]) -> str:
    return "[" + ", ".join(number(value) for value in values) + "]"


def fixed_mounts(model: ET.Element, parent: str) -> list[list[float]]:
    points = []
    for joint in model.findall("joint"):
        if joint.get("type") != "fixed" or joint.find("parent").get("link") != parent:
            continue
        origin = joint.find("origin")
        points.append(vector(origin, "xyz", 1000.0)[:2])
    return points


def render() -> str:
    arm = ET.parse(SO101).getroot()
    joints = {joint.get("name"): joint for joint in arm.findall("joint")}
    if set(JOINTS) - joints.keys():
        raise ValueError("canonical SO-101 model is missing a required joint")

    names = ", ".join(f'"{name}"' for name in JOINTS)
    xyz = []
    rpy = []
    limits = []
    for name in JOINTS:
        joint = joints[name]
        origin = joint.find("origin")
        limit = joint.find("limit")
        if vector(joint.find("axis"), "xyz") != [0.0, 0.0, 1.0]:
            raise ValueError(f"{name} no longer rotates around local Z")
        xyz.append(vector(origin, "xyz", 1000.0))
        rpy.append([math.degrees(value) for value in vector(origin, "rpy")])
        limits.append(
            [math.degrees(float(limit.get(key))) for key in ("lower", "upper")]
        )

    lekiwi = ET.parse(LEKIWI).getroot()
    mount = lekiwi.find("joint[@name='so101_mount']")
    if mount is None:
        raise ValueError("LeKiwi Xacro is missing so101_mount")
    mount_origin = mount.find("origin")
    lower_mounts = fixed_mounts(lekiwi, "base_plate_layer1-v5")
    upper_mounts = fixed_mounts(lekiwi, "base_plate_layer2-v3")

    lines = [
        "// Generated by generate_kinematics.py; do not edit.",
        f"joint_names = [{names}];",
        "joint_xyz = [" + ", ".join(scad_vector(values) for values in xyz) + "];",
        "joint_rpy = [" + ", ".join(scad_vector(values) for values in rpy) + "];",
        "joint_limits = [" + ", ".join(scad_vector(values) for values in limits) + "];",
        f"arm_mount_xyz = {scad_vector(vector(mount_origin, 'xyz', 1000.0))};",
        f"arm_mount_rpy = {scad_vector([math.degrees(value) for value in vector(mount_origin, 'rpy')])};",
        "base_lower_mounts = ["
        + ", ".join(scad_vector(point) for point in lower_mounts)
        + "];",
        "base_upper_mounts = ["
        + ", ".join(scad_vector(point) for point in upper_mounts)
        + "];",
        "function joint_index(name) = search([name], joint_names)[0];",
        "function joint_position(name) = joint_xyz[joint_index(name)];",
        "function joint_rotation(name) = joint_rpy[joint_index(name)];",
        "function joint_range(name) = joint_limits[joint_index(name)];",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if generated output is stale"
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated file: run {Path(__file__).name}")
        print(f"verified {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
