"""Generate OpenSCAD constants and concise mount documentation from one spec."""

import argparse
import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "cad/accessories/sensor_mount_spec.json"
SCAD_PATH = ROOT / "cad/accessories/sensor_mount_spec.scad"
DOC_PATH = ROOT / "cad/accessories/SENSOR_MOUNTS.md"


def outputs():
    spec = json.loads(SPEC_PATH.read_text())
    astra = spec["astra"]
    first, second = astra["plate_holes_mm"]
    spacing = math.dist(first[:2], second[:2])
    scad = (
        "// Generated by scripts/sync_sensor_mount_spec.py; edit sensor_mount_spec.json.\n"
        f"astra_pitch = {astra['pitch_deg']};\n"
        f"astra_camera_contact_height = {astra['camera_contact_height_mm']};\n"
        f"astra_m3_spacing = {spacing:.15g};\n"
    )
    lidar = spec["lidar"]
    doc = f"""# Sensor mounts

Generated from `sensor_mount_spec.json`; edit that file and run
`scripts/sync_sensor_mount_spec.py`.

- LD06 mount origin (m): `{lidar['mount_origin_m']}`
- LD06 body centre in mount (m): `{lidar['body_center_m']}`
- Astra plate holes (mm): `{astra['plate_holes_mm']}`
- Astra mount origin (m): `{astra['mount_origin_m']}`
- Astra pitch: `{astra['pitch_deg']} deg`
"""
    return {SCAD_PATH: scad, DOC_PATH: doc}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"stale generated sensor-mount file: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
